PRHomePage/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [url(r'^admin/', admin.site.urls),
               url(r'^siteapostas/', include('home.urls', namespace='home')),
               ]

home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
   login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
)

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    #url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'template_name': 'home/logout.html'}, name='logout'),
    #url(r'^register/$', views.register, name='register'),
    url(r'^personalpage/$', views.personalpage, name='personalpage'),
    url(r'^changepassword/$', views.changePassword, name='changepassword'),
    url(r'^exitMenor$', views.exitMenor, name='exitMenor'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^areacomum/$', views.areacomum, name='areacomum'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^$', views.returnHomepage, name='returnHomepage'),
    url(r'^aposta$', views.fazerAposta, name='fazerAposta'),
    url(r'^registo$', views.registo, name='registo'),
    url(r'^novoRegisto$', views.novoRegisto, name='novoRegisto'),
    url(r'^loginpage$', views.loginpage, name='loginpage'),
    url(r'^loginview$', views.loginview, name='loginview'),
    url(r'^logoutview/$',views.logoutview, name='logoutview'),
    url(r'^submeterpass/$', views.submeterpass, name='submeterpass'),
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),
    ]

home/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Utilizador(models.Model):
    user = models.OneToOneField(User)
    NIF = models.IntegerField(null=True)
    contacto = models.IntegerField(null=True)
    codigopostal = models.IntegerField(null=True)
    morada = models.CharField(max_length=200, null=True)
    localidade = models.CharField(max_length=50, null=True)
    pais = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.user.username

class Teste(models.Model):
    coluna1 = models.IntegerField()

home/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, HttpResponseRedirect, redirect
from django.core.urlresolvers import reverse
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDictKeyError
from .models import Utilizador
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm

def inicio(request):
    return render(request, 'home/inicio.html')

def exitMenor(request):
    return render(request, 'home/exitMenor.html')

def homepage(request):
    return render(request, 'home/homepage.html')

def returnHomepage(request):
    return HttpResponseRedirect(reverse('home/homepage.html'))

def personalpage(request):
    args = {}
    for each in User._meta.fields:
        args[each.name] = getattr(User, each.name)
    return render(request, 'home/personalpage.html', args)

def areacomum(request):
    return render(request, 'home/areacomum.html')

def admin(request):
    return render(request, 'home/admin.html')


def fazerAposta(request):
    return render(request, 'home/aposta.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'home/homepage.html')
    else:
        form = UserCreationForm()

    args = {'form':form}
    return render(request, 'home/reg_form.html', args)

def novoRegisto(request):
    if request.POST['input_username'] is '':
        context = {'invalid_user': True}
        return render(request, "home/registo.html", context)

    if request.POST['input_email'] is '':
        context = {'invalid_email': True}
        return render(request, "home/registo.html", context)

    if request.POST['input_password'] is '':
        context = {'invalid_pass': True}
        return render(request, "home/registo.html", context)

    if request.POST['input_name'] is '':
        context = {'invalid_name': True}
        return render(request, "home/registo.html", context)

    if request.POST['input_surname'] is '':
        context = {'invalid_last': True}
        return render(request, 'home/registo.html', context)
    else:
        try:
            fuser = User.objects.create_user(request.POST['input_username'], request.POST['input_email'],
                                             request.POST['input_password'])
            fuser.first_name = request.POST['input_name']
            fuser.last_name = request.POST['input_surname']
            fuser.save()
        except:
            context = {}
            context['same_user'] = True
            return render(request, 'home/registo.html', context)

        fuser = Utilizador(user=fuser)
        if request.POST['input_nif']:
            fuser.NIF = request.POST['input_nif']
        if request.POST['input_morada']:
            fuser.morada = request.POST['input_morada']
        if request.POST['input_codpostal']:
            fuser.codigopostal = request.POST['input_codpostal']
        if request.POST['input_contacto']:
            fuser.contacto = request.POST['input_contacto']
        if request.POST['input_loc']:
            fuser.localidade = request.POST['input_loc']
        if request.POST['input_pais']:
            fuser.pais = request.POST['input_pais']

        fuser.save()

        emaildestino = request.POST['input_email']
        destinatario = request.POST['input_name'] + " " + request.POST['input_surname']
        titulo = 'Email de confirmação de registo'
        mensagem = 'Bem vindo ao site de apostas ' + destinatario + "."
        send_mail(titulo, mensagem, settings.EMAIL_HOST_USER, [emaildestino], fail_silently=True)
        return render(request, 'home/homepage.html')


def registo(request):
    return render(request, 'home/registo.html')

def loginpage(request):
    return render(request, 'home/loginpage.html')

def loginview(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    context = {}
    if user is not None:
        login(request, user)
        args = {}
        for each in User._meta.fields:
            args[each.name] = getattr(User, each.name)
        return render(request, 'home/personalpage.html', args)

    else:
        context['noUser'] = True
        return render(request, "home/loginpage.html", context)

def logoutview(request):
    logout(request)
    return render(request, 'home/logout.html')


def changePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.POST, user=request.user)

        if form.is_valid():
            form.save()
            return redirect('/siteapostas/personalpage')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'home/changepassword.html')

def submeterpass(request):
    acco = get_object_or_404(Utilizador, user=request.user)
    context = {}
    context['acc'] = acco
    if request.user.is_authenticated:
        try:
            if request.user.check_password(request.POST['oldpassword']):
                if request.POST['newpassword'] == request.POST['confnewpassword']:
                    request.user.set_password(request.POST['newpassword'])
                    request.user.save()

                    return render(request, "home/personalpage.html")
                else:
                    context['no_match'] = True
                    return render(request, "home/changepassword.html", context)
            else:
                context['old'] = True
                return render(request, "home/changepassword.html", context)

        except MultiValueDictKeyError:
            return HttpResponseRedirect(reverse('home:changepassword'))
    else:
        return HttpResponse("É necessário estar autenticado.")

home/templates/home/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Administração</title>
</head>
<body>
<h1>estou no admin</h1>
<li><a href="{% url 'home:homepage' %}"> de volta para homepage</a></li>
</body>
</html>

home/templates/home/areacomum.html
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Area Pessoal</title>
</head>
<body>
<h1>Bem vindo ao site de Apostas, faça login para começar a apostar</h1>

<li><a href="{% url 'home:returnHomepage' %}"> de volta para homepage</a></li>
<li><a href="{% url 'home:loginpage' %}"> fazer login</a></li>
<li><a href="{% url 'home:password_reset' %}"> recuperar pass</a></li>
<li><a href="{% url 'home:registo' %}"> Novo Registo</a></li>

<h1>Aqui ficam imagens publicidade!!!</h1>
</body>
</html>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Site de Apostas{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>Apostando</h1>
      {% if user.is_authenticated %}
          <p>Bem vindo, {{ user.username }}  <a href="{% url 'home:logoutview' %}">[Sair]</a></p>
      {% else %}
           <p>Bem vindo, Convidado <a href="{% url 'home:loginpage' %}">[login]</a></p>
      {% endif %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

home/templates/home/changepassword.html
{% extends 'base.html' %}
{% block content %}
    <title>Mudar password</title>
</head>
<body>
<form action="{% url 'home:submeterpass'%}" method="post">
            {% csrf_token %}
            <input type="password" placeholder="Password actual" name = "oldpassword" required/>
            {% if old %}
            Password errada.
            {% endif %}
            <input type="password" placeholder="Nova Password" name = "newpassword" required/>
            <input type="password" placeholder="Nova Password" name = "confnewpassword" required/>
            {% if no_match %}
            A password de confirmação não está igual.
            {% endif %}
            <input type="submit" value="Submit"/>
        </form>

<p><a href="{% url 'home:personalpage' %}"><button type="button">Voltar para a pagina pessoal</button></a></p>
</body>
{% endblock %}

home/templates/home/exitMenor.html
<h1>Volta daqui a uns anos!</h1>

home/templates/home/homepage.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
<h1>estou na pagina pessoal </h1>
<h2>Bem vindo, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>


<li><a href="{% url 'home:admin' %}"> Link para conta de administração</a></li>
<li><a href="{% url 'home:password_reset' %}"> recuperar pass</a></li>
<li><a href="{% url 'home:fazerAposta' %}"> Fazer aposta</a></li>
<li><a href="{% url 'home:registo' %}"> Novo Registo</a></li>

</body>
</html>
{% endblock %}

home/templates/home/inicio.html
<h1>Que idade tens?</h1>

<a href="{% url 'home:exitMenor' %}"> Menos de 18 </a>
<br></br>
<a href="{% url 'home:areacomum' %}"> Mais de 18 </a>

home/templates/home/loginpage.html
{% block content %}
  <h2>Entrar no site</h2>
  {% if form.errors %}
    <p style="color: red">O username e a password não foram encontradas. Tenta outra vez.</p>
  {% endif %}
  <form method="post" action="{% url 'home:loginview' %}">
    {% csrf_token %}
  <p>Username :  <input type="text" autocomplete="off" name="username"></p>
  <p>Password :  <input type="password" autocomplete="off" name="password"></p>
      {% if noUser %}
      Login sem sucesso. Tente novamente.
      {% endif %}
<br><br>
<input type="submit" value="entrar">
  <a href="{% url 'home:registo' %}">Novo na página? Regista-te</a><br>

  </form>
{% endblock %}

home/templates/home/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
<h2>Obrigado pela sua visita. Até breve.</h2>
</form>
</body>
</html>

home/templates/home/password_reset.html
{% block content %}
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

home/templates/home/password_reset_done.html
{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

home/templates/home/personalpage.html
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personal Page</title>
</head>
<body>
<h1>Bem vindo, {{ user.get_full_name }} !</h1>
<ul>
    {{ user.email }}
</ul>


<li><a href="{% url 'home:changepassword' %}"> mudar pass</a></li>

</body>
</html>
{% endblock %}

home/templates/home/reg_form.html
{% block body %}
<form action="{% url 'home:register'%}" method="post">
{% csrf_token %}
{{ form.as_p }}

<button type="submit">Registar</button>
</form>

{% endblock %}

home/templates/home/registo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Novo Registo</title>
</head>
<body>
<h1> Bem vindo ao site de Apostas. Não perca mais tempo e faça já o seu registo.</h1>

    <form action="{% url 'home:novoRegisto'%}" method="post">
        {% csrf_token %}
        <p><strong>Nome :  </strong><input type="text" placeholder="Nome" name="input_name" required/></p>
        <p><strong>Apelido :  </strong><input type="text" placeholder="Apelido" name="input_surname" required/></p>
        <p><strong>Username :  </strong><input type="text" autocomplete="off" placeholder="Username" name="input_username"required/></p>
            {% if same_user %}
            <strong>Já existe um utilizador com esse username.</strong>
            {% endif %}
        <p><strong>Password :  </strong><input type="password" autocomplete="off" placeholder="Password" name="input_password" pattern=".{5,}" title="Password com 8 caracteres obrigatórios." required/></p>
        <p><strong>Email :  </strong><input type="email" placeholder="Email" name="input_email" required/></p>
        <p><strong>NIF :  </strong><input type="number" placeholder="NIF" name="input_nif"/ required></p>
        <p><strong>Contacto :  </strong><input type="number" placeholder="Contacto" name="input_contacto"/></p>
        <p><strong>Código Postal :  </strong><input type="number" placeholder="Código Postal" name="input_codpostal"/></p>
        <p><strong>Morada :  </strong><input type="text" placeholder="Morada" name="input_morada"/></p>
        <p><strong>Localidade :  </strong><input type="text" placeholder="Localidade" name="input_loc"/></p>
        <p><strong>País :  </strong><input type="text" placeholder="País" name="input_pais"/></p>

            <br><input type="submit" value="Registar"/>&nbsp;&nbsp;<button type="reset" value="Reset">Apagar Valores</button>
        </form>
<p><a href="{% url 'home:areacomum' %}"><button type="button">Voltar a homepage</button></a></p>

</body>
</html>