PRHomePage/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [url(r'^admin/', admin.site.urls),
               url(r'^siteapostas/', include('home.urls', namespace='home')),
               ]

areas/urls.py
from django.conf.urls import url
from . import views

app_name = 'areas'
urlpatterns = [
    url(r'^$', views.areacomum, name='areacomum'),
    url(r'^apostar/$', views.apostar, name='apostar'),
    url(r'^areapessoal/$', views.areapessoal, name='areapessoal'),
    url(r'^carregarsaldo$', views.carregarsaldo, name='carregarsaldo'),
    url(r'^editardados/$', views.editardados, name='editardados'),
    url(r'^mostardados$', views.mostrardados, name='mostrardados'),
        ]

home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
   login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
)

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    #url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'template_name': 'home/logout.html'}, name='logout'),
    #url(r'^register/$', views.register, name='register'),
    url(r'^personalpage/$', views.personalpage, name='personalpage'),
    url(r'^changepassword/$', views.changePassword, name='changepassword'),
    url(r'^exitMenor$', views.exitMenor, name='exitMenor'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^areacomum/$', views.areacomum, name='areacomum'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^$', views.returnHomepage, name='returnHomepage'),
    url(r'^aposta$', views.fazerAposta, name='fazerAposta'),
    url(r'^registo$', views.registo, name='registo'),
    url(r'^novoRegisto$', views.novoRegisto, name='novoRegisto'),
    url(r'^loginpage$', views.loginpage, name='loginpage'),
    url(r'^loginview$', views.loginview, name='loginview'),
    url(r'^logoutview/$',views.logoutview, name='logoutview'),
    url(r'^submeterpass/$', views.submeterpass, name='submeterpass'),
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),
    ]

areas/models.py
from django.db import models

'''
import datetime



class User(models.Model):
    user_name = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    email = models.EmailField()

    registo_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.questao_texto

    def createUserid(self):
        return

'''

areas/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from django.utils import timezone

#from .models import Questao, Opcao

def areacomum(request):
    return render(request, 'areas/areacomum.html')

def apostar(request):
    return render(request, 'areas/apostar.html')

def areapessoal(request):
    return render(request, 'areas/areapessoal.html')

def mostrardados(request):
    return render(request, 'areas/mostrardados.html')

def editardados(request):
    return render(request, 'areas/editardados.html')

def carregarsaldo(request):
    return render(request, 'areas/carregarsaldo.html')

areas/templates/areas/apostar.html
<p>Aqui deverá existir uma ligação à função do Vasco para construtor de chaves e uma ligação à
    tabela de historico de apostas</p>


<a href="{% url 'areas:areacomum'%}">Ir para Área Comum</a><br>
</br>

areas/templates/areas/areacomum.html
<h1>Área Comum</h1>

<a href="{% url 'areas:areapessoal'%}">Ir para Área Pessoal</a><br>
</br>


<a href="{% url 'areas:apostar'%}">Fazer Aposta</a><br>
</br>

areas/templates/areas/areapessoal.html
<a href="{% url 'areas:mostrardados'%}">Mostrar Dados Pessoais</a><br>
</br>

<a href="{% url 'areas:editardados'%}">Editar Dados Pessoais</a><br>
</br>

<h2>Tabela com histórico de apostas</h2><br>
</br>

<h2>Campo com Saldo Atual</h2>

<a href="{% url 'areas:carregarsaldo'%}">Carregar Saldo Conta</a><br>
</br>

<a href="{% url 'areas:areacomum'%}">Ir para Área Comum</a><br>
</br>

areas/templates/areas/carregarsaldo.html
<p>Aqui teremos uma lista com 3 opções de carregamento que o utilizador carregando acrescenta
dinheiro à conta automaticamente
    (no real deveria gerar referência multibanco e após verificação de conta entrava no saldo)
</p>

<a href="{% url 'areas:areapessoal'%}">Ir para Área Pessoal</a><br>
</br>

areas/templates/areas/editardados.html
<a href="{% url 'areas:areapessoal'%}">Ir para Área Pessoal</a><br>
</br>

areas/templates/areas/mostrardados.html
<p>Aqui deverá existir uma tabela com a informação do utilizador</p>

<a href="{% url 'areas:areapessoal'%}">Ir para Área Pessoal</a><br>
</br>